# Generated by Django 3.2.20 on 2023-10-21 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimeincidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('crimetype', models.CharField(db_column='CrimeType', max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(db_column='Location', max_length=255)),
                ('description', models.TextField(db_column='Description')),
            ],
        ),
    ]
