# Generated by Django 4.2.6 on 2023-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_auto_20231023_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimeincidents',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crimeincidents',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
