# Generated by Django 4.2.6 on 2023-10-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0004_alter_crimeincidents_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimeincidents',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
